# -*- coding: utf-8 -*-
"""ProjekMTK.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SwhGK3WxmwaN6VlfrpxgYXTjDI0vGOaH
"""

import pandas as pd
import matplotlib.pyplot as plt


# ============================================================
# 1. BACA DATA
# ============================================================

print("\n" + "=" * 60)
print("1. BACA DATA")
print("=" * 60)

df = pd.read_excel("3TIB_05_PemahamanPaliatif.xlsx")

print("Jumlah responden :", len(df))
print("Jumlah kolom     :", len(df.columns))


# ============================================================
# 2. RENAME KOLOM
# ============================================================

print("\n" + "=" * 60)
print("2. RENAME KOLOM")
print("=" * 60)

k = df.columns

df = df.rename(columns={
    k[2]: "Usia",
    k[3]: "Pendidikan",
    k[4]: "Status",
    k[5]: "Kerabat_kanker",
    k[6]: "Pernah_merawat",
    k[7]: "Pernah_dengar",
    k[8]: "Pemahaman_diri",
    k[33]: "Cemas_merawat",
    k[34]: "Penting_edukasi",
    k[35]: "Animasi_membantu",
    k[36]: "Nyaman_visual"
})

k = df.columns

print("Kolom berhasil diubah.")


# ============================================================
# 3. MENGHITUNG SKOR PENGETAHUAN
# ============================================================

print("\n" + "=" * 60)
print("3. SKOR PENGETAHUAN")
print("=" * 60)

# Kolom 9 sampai 22 = 14 pertanyaan pengetahuan
# Jawaban "Benar" = 1
# Jawaban selain "Benar" = 0

df["Skor_pengetahuan"] = (
    (df[k[9:23]] == "Benar").sum(axis=1)
)

print("Jumlah pertanyaan pengetahuan :", len(k[9:23]))
print("Skor maksimum                 :", 14)
print("Kolom hasil                   : Skor_pengetahuan")


# ============================================================
# 4. MENGHITUNG SKOR KHAWATIR
# ============================================================

print("\n" + "=" * 60)
print("4. SKOR KHAWATIR")
print("=" * 60)

# Kolom 23 sampai 27 = 5 pertanyaan
df["Skor_khawatir"] = df[k[23:28]].sum(axis=1)

print("Jumlah pertanyaan :", len(k[23:28]))
print("Skor minimum      : 5")
print("Skor maksimum      : 25")
print("Kolom hasil       : Skor_khawatir")


# ============================================================
# 5. MENGHITUNG SKOR KESIAPAN
# ============================================================

print("\n" + "=" * 60)
print("5. SKOR KESIAPAN")
print("=" * 60)

# Kolom 28 sampai 32 = 5 pertanyaan
df["Skor_kesiapan"] = df[k[28:33]].sum(axis=1)

print("Jumlah pertanyaan :", len(k[28:33]))
print("Skor minimum      : 5")
print("Skor maksimum      : 25")
print("Kolom hasil       : Skor_kesiapan")


# ============================================================
# 6. MENAMPILKAN HASIL SKOR
# ============================================================

print("\n" + "=" * 60)
print("6. HASIL PERHITUNGAN SKOR")
print("=" * 60)

print(
    df[
        [
            "Skor_pengetahuan",
            "Skor_khawatir",
            "Skor_kesiapan"
        ]
    ].head(10)
)


# ============================================================
# 7. STATISTIK DESKRIPTIF
# ============================================================

print("\n" + "=" * 60)
print("7. STATISTIK DESKRIPTIF")
print("=" * 60)

kolom = [
    "Usia",
    "Pemahaman_diri",
    "Skor_pengetahuan",
    "Skor_khawatir",
    "Skor_kesiapan",
    "Cemas_merawat",
    "Penting_edukasi",
    "Animasi_membantu",
    "Nyaman_visual"
]

hasil = pd.DataFrame({
    "N": df[kolom].count(),
    "Mean": df[kolom].mean(),
    "Median": df[kolom].median(),
    "Modus": df[kolom].mode().iloc[0],
    "SD": df[kolom].std(),
    "Min": df[kolom].min(),
    "Maks": df[kolom].max(),
    "Q1": df[kolom].quantile(0.25),
    "Q3": df[kolom].quantile(0.75),
    "Skewness": df[kolom].skew()
}).round(2)

print(hasil)


# ============================================================
# 8. FREKUENSI VARIABEL KATEGORIK
# ============================================================

print("\n" + "=" * 60)
print("8. FREKUENSI VARIABEL KATEGORIK")
print("=" * 60)

for kol in [
    "Pendidikan",
    "Status",
    "Pernah_merawat",
    "Pernah_dengar"
]:

    print("\n---", kol, "---")

    frekuensi = pd.DataFrame({
        "N": df[kol].value_counts(),
        "%": df[kol]
            .value_counts(normalize=True)
            .mul(100)
            .round(1)
    })

    print(frekuensi)


# ============================================================
# 9. KELOMPOK USIA
# ============================================================

print("\n" + "=" * 60)
print("9. KELOMPOK USIA")
print("=" * 60)

df["Kelompok_usia"] = pd.cut(
    df["Usia"],
    [0, 17, 25, 35, 45, 100],
    labels=[
        "<18",
        "18-25",
        "26-35",
        "36-45",
        ">45"
    ]
)

print(df["Kelompok_usia"].value_counts().sort_index())


# ============================================================
# 10. KATEGORI SKOR PENGETAHUAN
# ============================================================

print("\n" + "=" * 60)
print("10. KATEGORI SKOR PENGETAHUAN")
print("=" * 60)

df["Kategori_pengetahuan"] = pd.cut(
    df["Skor_pengetahuan"],
    [-1, 4, 9, 14],
    labels=[
        "Rendah",
        "Sedang",
        "Tinggi"
    ]
)

print(
    df["Kategori_pengetahuan"]
    .value_counts()
    .sort_index()
)


# ============================================================
# 11. KATEGORI SKOR KHAWATIR
# ============================================================

print("\n" + "=" * 60)
print("11. KATEGORI SKOR KHAWATIR")
print("=" * 60)

df["Kategori_khawatir"] = pd.cut(
    df["Skor_khawatir"],
    [0, 11, 18, 25],
    labels=[
        "Rendah",
        "Sedang",
        "Tinggi"
    ]
)

print(
    df["Kategori_khawatir"]
    .value_counts()
    .sort_index()
)


# ============================================================
# 12. KATEGORI SKOR KESIAPAN
# ============================================================

print("\n" + "=" * 60)
print("12. KATEGORI SKOR KESIAPAN")
print("=" * 60)

df["Kategori_kesiapan"] = pd.cut(
    df["Skor_kesiapan"],
    [0, 11, 18, 25],
    labels=[
        "Rendah",
        "Sedang",
        "Tinggi"
    ]
)

print(
    df["Kategori_kesiapan"]
    .value_counts()
    .sort_index()
)


# ============================================================
# 13. FREKUENSI SETIAP PERTANYAAN PENGETAHUAN
# ============================================================

print("\n" + "=" * 60)
print("13. FREKUENSI JAWABAN SETIAP PERTANYAAN")
print("=" * 60)

for i, p in enumerate(k[9:23]):

    print(
        f"P{i+1}:",
        df[p].value_counts().to_dict()
    )


# ============================================================
# 14. RATA-RATA BERDASARKAN PERNAH MENDENGAR
# ============================================================

print("\n" + "=" * 60)
print("14. RATA-RATA BERDASARKAN PERNAH MENDENGAR")
print("=" * 60)

print(
    df.groupby("Pernah_dengar")[
        [
            "Skor_pengetahuan",
            "Skor_khawatir",
            "Skor_kesiapan"
        ]
    ].mean().round(2)
)


# ============================================================
# 15. RATA-RATA BERDASARKAN PERNAH MERAWAT
# ============================================================

print("\n" + "=" * 60)
print("15. RATA-RATA BERDASARKAN PERNAH MERAWAT")
print("=" * 60)

print(
    df.groupby("Pernah_merawat")[
        [
            "Skor_pengetahuan",
            "Skor_khawatir",
            "Skor_kesiapan"
        ]
    ].mean().round(2)
)


# ============================================================
# 16. RATA-RATA BERDASARKAN KATEGORI PENGETAHUAN
# ============================================================

print("\n" + "=" * 60)
print("16. RATA-RATA BERDASARKAN KATEGORI PENGETAHUAN")
print("=" * 60)

print(
    df.groupby("Kategori_pengetahuan")[
        [
            "Skor_khawatir",
            "Skor_kesiapan"
        ]
    ].mean().round(2)
)


# ============================================================
# 17. HISTOGRAM USIA
# ============================================================

print("\n" + "=" * 60)
print("17. MEMBUAT HISTOGRAM USIA")
print("=" * 60)

df["Usia"].plot(
    kind="hist",
    bins=range(10, 60, 5),
    color="#2E75B6",
    edgecolor="white"
)

plt.title("Histogram Usia Responden")
plt.xlabel("Usia (tahun)")
plt.ylabel("Frekuensi")

plt.savefig(
    "g_hist_usia.png",
    dpi=150,
    bbox_inches="tight"
)

plt.show()
plt.clf()


# ============================================================
# 18. HISTOGRAM SKOR
# ============================================================

print("\n" + "=" * 60)
print("18. MEMBUAT HISTOGRAM SKOR")
print("=" * 60)

bins = range(0, 27, 2)

for kol, judul in [
    ("Skor_pengetahuan", "Skor Pengetahuan"),
    ("Skor_khawatir", "Skor Kekhawatiran"),
    ("Skor_kesiapan", "Skor Kesiapan")
]:

    df[kol].plot(
        kind="hist",
        bins=bins,
        color="#2E75B6",
        edgecolor="white"
    )

    plt.axvline(
        df[kol].mean(),
        color="red",
        linestyle="--",
        label="Mean"
    )

    plt.title("Histogram " + judul)
    plt.xlabel(judul)
    plt.ylabel("Frekuensi")
    plt.legend()

    plt.savefig(
        "g_hist_" + kol + ".png",
        dpi=150,
        bbox_inches="tight"
    )

    plt.show()
    plt.clf()


# ============================================================
# 19. BAR CHART PERNAH MENDENGAR
# ============================================================

print("\n" + "=" * 60)
print("19. BAR CHART PERNAH MENDENGAR")
print("=" * 60)

df["Pernah_dengar"].value_counts().plot(
    kind="bar",
    color=["#C55A11", "#548235"],
    rot=0
)

plt.title(
    "Pernah Mendengar Istilah Perawatan Paliatif"
)

plt.xlabel("Pernah mendengar")
plt.ylabel("Jumlah responden")

plt.savefig(
    "g_dengar.png",
    dpi=150,
    bbox_inches="tight"
)

plt.show()
plt.clf()


# ============================================================
# 20. BOXPLOT
# ============================================================

print("\n" + "=" * 60)
print("20. BOXPLOT SKOR")
print("=" * 60)

df[
    [
        "Skor_pengetahuan",
        "Skor_khawatir",
        "Skor_kesiapan"
    ]
].plot(
    kind="box",
    subplots=True,
    layout=(1, 3),
    figsize=(8, 3.5)
)

plt.savefig(
    "g_box.png",
    dpi=150,
    bbox_inches="tight"
)

plt.show()
plt.clf()


# ============================================================
# 21. GRAFIK JAWABAN PERTANYAAN PENGETAHUAN
# ============================================================

print("\n" + "=" * 60)
print("21. GRAFIK JAWABAN PERTANYAAN PENGETAHUAN")
print("=" * 60)

jawaban = pd.DataFrame({
    f"P{i+1}": df[p].value_counts()
    for i, p in enumerate(k[9:23])
}).T

jawaban = jawaban[
    ["Benar", "Tidak Tahu", "Salah"]
].fillna(0)

jawaban.plot(
    kind="barh",
    stacked=True,
    color=[
        "#548235",
        "#BFBFBF",
        "#C00000"
    ],
    figsize=(7, 5)
)

plt.title(
    "Jawaban per Pernyataan Pengetahuan"
)

plt.xlabel("Jumlah responden")

plt.gca().invert_yaxis()

plt.savefig(
    "g_items.png",
    dpi=150,
    bbox_inches="tight"
)

plt.show()
plt.clf()


# ============================================================
# 22. SELESAI
# ============================================================

print("\n" + "=" * 60)
print("SEMUA ANALISIS SELESAI")
print("=" * 60)