# -*- coding: utf-8 -*-
"""StatistikaPert4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XI0h_VD3kV7g-5Wo88Ra3AFNrYUQwzE3
"""

from google.colab import files

uploaded = files.upload()

# Tabel Frekuensi Grade
datafrq = pd.crosstab(index=df["Grade"], columns="Frekuensi")

print("Tabel Frekuensi Grade:")
print(datafrq)

# Grafik Garis
datafrq.plot()

# Grafik Batang
datafrq.plot(kind="bar")

# Pie Chart
datafrq.plot(
    kind="pie",
    y="Frekuensi",
    autopct="%1.1f%%",
    legend=False
)

# Statistika Deskriptif
df["Final Score"] = pd.to_numeric(
    df["Final Score"],
    errors="coerce"
)

dt = df["Final Score"]

stats = dt.describe()

stats["Standard Error"] = dt.sem()
stats["Median"] = dt.median()
stats["Mode"] = dt.mode().iloc[0]
stats["Variance"] = dt.var()
stats["Range"] = dt.max() - dt.min()
stats["Skewness"] = dt.skew()
stats["Kurtosis"] = dt.kurtosis()

print("\nStatistika Deskriptif:")
print(stats)

# Export ke Excel
with pd.ExcelWriter("hasil_analisis.xlsx", engine="openpyxl") as writer:

    # Tabel Frekuensi Grade
    datafrq.to_excel(
        writer,
        sheet_name="Frekuensi Grade"
    )

    # Statistika Deskriptif
    stats.to_excel(
        writer,
        sheet_name="Statistika Deskriptif"
    )

print("Data berhasil diekspor ke hasil_analisis.xlsx")